services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: SistemaComercio
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - db

volumes:
  pg_data:
